# This is a basic workflow to help you get started with Actions

name: CI

on:
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start
    steps:
    - name: Checkout
      uses: actions/checkout@v2  # 使用具体的版本而不是 master

    - name: Set up Python
      uses: actions/setup-python@v2  # 设置 Python 环境
      with:
        python-version: '3.8'  # 指定 Python 版本，可以根据需要调整

    - name: Install requests and nacl  # 安装 requests 模块
      run: |
        python -m pip install --upgrade pip  # 升级 pip
        pip install requests  # 安装 requests
        pip install pynacl  # 如果需要 nacl，可以在此安装

    - name: Run API  # API 调用
      env: 
        # GitHub 的账号信息
        GH_TOKEN: ${{ secrets.GH_TOKEN }} 
        GH_REPO: ${{ github.repository }}
        # 以下是微软的账号信息
        APP_NUM: ${{ secrets.APP_NUM }} 
        MS_TOKEN: ${{ secrets.MS_TOKEN }} 
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        # 发送信息
        url_bark: ${{ secrets.URL_BARK }}
        url_wechat: ${{ secrets.URL_WECHAT }}
        url: ${{ secrets.URL }}
        appToken: ${{ secrets.APPTOKEN }}
        UID: ${{ secrets.UID }}
      run: |
        python index.py
