# This is a basic workflow to help you get started with Actions


name: AutoRun

on:
  release:
    types: [published]
  schedule:
    - cron: '0 8-18 * * 1-6'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2  # 使用具体的版本而不是 master

    - name: Set up Python
      uses: actions/setup-python@v2  # 设置 Python 环境
      with:
        python-version: '3.8'  # 指定 Python 版本，根据需要可以调整

    - name: Upgrade pip and Install requests and nacl  # 安装请求模块
      run: |
        python -m pip install --upgrade pip  # 升级 pip
        pip install requests pynacl  # 安装 requests 和 nacl

    - name: Run API  # API 调用
      env: 
        # GitHub 的账号信息
        GH_TOKEN: ${{ secrets.GH_TOKEN }} 
        GH_REPO: ${{ github.repository }}
        # 以下是微软的账号信息
        APP_NUM: ${{ secrets.APP_NUM }} 
        MS_TOKEN: ${{ secrets.MS_TOKEN }} 
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        # 发送信息
        url_bark: ${{ secrets.URL_BARK }}
        url_wechat: ${{ secrets.URL_WECHAT }}
        url: ${{ secrets.URL }}
        appToken: ${{ secrets.APPTOKEN }}
        UID: ${{ secrets.UID }}
        telegram_token: ${{ secrets.TELEGRAM_TOKEN }}
        telegram_chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        python index.py
